name: Java CI avec Maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configuration de Java 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build avec Maven
      run: mvn -B clean compile

    - name: Tests unitaires
      run: mvn -B test

    - name: Rapport de tests
      run: mvn -B surefire-report:report
      if: always()

    - name: Publication des résultats de tests
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: rapports-tests
        path: target/site/

    - name: Mise en cache des packages Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
